//
//  UIFont+Project.swift
//
//  Generated by Zeplin on 5/30/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIFont {
    
    // MARK: App Partner Font Styles
    
    
    // MARK: Zeplin Font Styles
    
    class func helveticaNeueBold17Font() -> UIFont? {
        return UIFont(name: "HelveticaNeue-Bold", size: 17.0)
    }
    
    class func helveticaNeueMedium17Font() -> UIFont? {
        return UIFont(name: "HelveticaNeue-Medium", size: 17.0)
    }
    
    class func helveticaNeue17Font() -> UIFont? {
        return UIFont(name: "HelveticaNeue", size: 17.0)
    }
    
    class func helveticaNeue13Font() -> UIFont? {
        return UIFont(name: "HelveticaNeue", size: 13.0)
    }
}
