# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!

def app_pods
    pod 'SDWebImage'
    pod 'Alamofire'
    pod 'GoogleAnalytics'
    pod 'NMSSH'
    pod 'JVFloatLabeledTextField'

end
 
target ‘WallE’ do
    app_pods
end
 
target ‘WallETests' do
    app_pods
end